//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuariqueRest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Huarique
    {
        public int Id { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public string TIPO { get; set; }
        public Nullable<decimal> RANGO { get; set; }
        public string DISTRITO { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO { get; set; }
        public string HORARIO { get; set; }
        public Nullable<int> ESTADO { get; set; }
    }
}
